#!/bin/bash
# dotnet publish -c Release -r linux-x64 --self-contained false -o ./publish
#   -p:PublishSingleFile=true
#   linux-x64 \ for linux
#   linux-musl-x64 \ for alpine
    # -o ./publish\
dotnet publish -r \
    linux-x64 \
    -c Release \
    --self-contained true \
    -p:IncludeNativeLibrariesForSelfExtract=true \
    -p:UseAppHost=true \
    -p:DebugType=None \
    -p:DebugSymbols=false
